version: 2
jobs:
  build:
    docker:
      - image: java:openjdk-8

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date